[variables]
PHP_VERSION = "8.3"

[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.intl",
  "php83Extensions.zip",
  "php83Extensions.mbstring",
  "php83Extensions.opcache",
  "nodejs_20"
]

[phases.build]
commands = [
  "composer install --ignore-platform-req=ext-intl --ignore-platform-req=ext-zip --optimize-autoloader --no-scripts --no-interaction",
  "npm install",
  "npm run build"
]


[phases.start]
commands = [
  "php -S 0.0.0.0:$PORT -t public"
]

