[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.intl",
  "php83Extensions.zip",
  "php83Extensions.mbstring",
  "php83Extensions.opcache",
  "nodejs_20"
]

[phases.build]
commands = [
  "composer install --optimize-autoloader --no-interaction",
  "npm ci",
  "npm run build"
]

[phases.start]
command = "php artisan serve --host=0.0.0.0 --port=$PORT"
